version: "3"
services:
  postgres:
    image: postgres:12.1
    ports:
      - "8001:5432"
    restart: always
    environment:
      POSTGRES_USER: user
    volumes:
      - ./init:/docker-entrypoint-initdb.d
